CREATE TABLE IF NOT EXISTS animal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(255),
    edad INT NOT NULL,
    especie VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    raza VARCHAR(255) NOT NULL
);